# https://testdriven.io/blog/deploying-django-to-heroku-with-docker/#gitlab-ci
# this file was used prior to moving the repo away from gitlab and back to GitHub
# GitHub actions are used for CI/CD
# for reference purposes this file has been left in the repo

stages:
  - build
  - test
  - deploy

variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:latest || true
    - docker build
      --cache-from $IMAGE:latest
      --tag $IMAGE:latest
      --file ./Dockerfile
      "."
    - docker push $IMAGE:latest

test:
  stage: test
  image: $IMAGE:latest
  services:
    - name: postgres:latest
      alias: postgres
  variables:
    POSTGRES_DB: test
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
    DATABASE_URL: postgres://runner@postgres:5432/test
  script:
    - pytest
    - flake8 secure_my_spot/ app/ --max-line-length=100 --exclude=__init__.py,migrations
    - black secure_my_spot/ app/ --check --extend-exclude=migrations
    - isort secure_my_spot/ app/ --check

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    HEROKU_APP_NAME: secure-my-spot-api
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_AUTH_TOKEN