# run this yml file from the CLI with: docker-compose -f docker-compose-dev.yml up -d
# connect to:
# db: docker-compose -f docker-compose-dev.yml exec db psql --username=svengerlach --dbname=secure_my_spot_dev
# db: docker exec -it [container name] psql --username=svengerlach --dbname=secure_my_spot_dev


version: "3.8"

services:
  web:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:12.0-alpine
    restart: on-failure
