# By default, docker-compose reads two files, the docker-compose.yml and the
# docker-compose.override.yml

version: "3.8"

services:
  api:
    volumes:
      - .:/app/

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery_worker:
    volumes:
      - .:/app/

volumes:
  postgres_data: