# By default, docker-compose reads two files, the docker-compose.yml and the
# docker-compose.override.yml

version: "3.8"

services:
  web:
    volumes:
      - .:/app/
    env_file:
      - .env

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  worker:
    volumes:
      - .:/app
    env_file:
      - .env

  broker:
    env_file:
      - .env

  redis:
    env_file:
      - .env

volumes:
  postgres_data: