version: "3.8"

services:
  web:
    environment:
      - ENV=development

      # db variables
      - DB_NAME=secure_my_spot_dev
      - DB_USER=svengerlach
      - DB_PASSWORD=123456789
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET=${DJANGO_SECRET_KEY}

#      - POSTGRES_USER=svengerlach
#      - POSTGRES_PASSWORD=123456789
#      - POSTGRES_DB=secure_my_spot_dev
      # prevents Python from writing pyc files to disc
#      - PYTHONDONTWRITEBYTECODE=1
      # prevents Python from buffering stdout and stderr (
#      - EPYTHONUNBUFFERED=1