# run this yml file from the CLI with: docker-compose -f docker-compose-dev.yml up -d
# connect to:
# db: docker-compose -f docker-compose-dev.yml exec db psql --username=svengerlach --dbname=secure_my_spot_dev
# db: docker exec -it [container name] psql --username=svengerlach --dbname=secure_my_spot_dev


version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=svengerlach
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=secure_my_spot_dev

volumes:
  postgres_data: