# This docker-compose expands on the base one by passing on ENVs from the local container
# environment on Github Actions. Also, it does not include the volume setting as the Github
# environment does not have a pre-set space.
# Source: https://github.community/t/how-to-use-docker-compose-with-github-actions/16850/3

version: "3.8"

services:
  web:
    environment:
      - ENV

      # db variables
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET

      # Django settings.py
      - DJANGO_SETTINGS_MODULE

      # Python settings
      - PYTHONUNBUFFERED
      - PYTHONDONTWRITEBYTECODE

      # rabbit settings
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - REDIS_PASSWORD

      # Stripe settings
      - STRIPE_API_TEST_KEY

  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  worker:
    environment:
      - ENV

      # db variables
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET

      # Django settings.py
      - DJANGO_SETTINGS_MODULE

      # Python settings
      - PYTHONUNBUFFERED
      - PYTHONDONTWRITEBYTECODE

      # rabbit settings
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - REDIS_PASSWORD

      # Stripe settings
      - STRIPE_API_TEST_KEY

  broker:
    environment:
      # rabbit settings
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  redis:
    environment:
      - REDIS_PASSWORD