version: "3.8"

services:
  web:
    volumes:
      - .:/app/
    env_file:
      - .env
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data: