# run this yml file from the CLI with: docker-compose up -d
# connect to:
# db: docker-compose exec db psql --username=svengerlach --dbname=secure_my_spot_dev
# db: docker exec -it [container name] psql --username=svengerlach --dbname=secure_my_spot_dev
# source for rabbit / redis: https://github.com/MexsonFernandes/Asynchronous_Tasks-Django-Celery-RabbitMQ-Redis/blob/master/docker-compose.yml


version: "3.8"

services:
  # django service
  api:
    build: .
#    image: api-img:latest
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 3001:8000
    depends_on:
      - db
      - celery_worker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      STRIPE_API_TEST_KEY: ${STRIPE_API_TEST_KEY}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    networks:
      - main_network

  # Database postgres service
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - main_network

  # Celery service
  celery_worker:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    # todo: auto-reload should not be used for production
    # command: python manage.py celery_autoload
    # statedb: https://docs.celeryproject.org/en/stable/userguide/workers.html#persistent-revokes
    command: celery -A secure_my_spot.celeryconf worker --loglevel=INFO
    depends_on:
      - db
      - rabbit-broker
      - redis
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      STRIPE_API_TEST_KEY: ${STRIPE_API_TEST_KEY}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    networks:
      - main_network

  # Broker service provided by RabbitMQ
  rabbit-broker:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"  # We forward this port because it's useful for debugging
      - "15672:15672"  # Here, we can access RabbitMQ management plugin
    networks:
      - main_network

  # Backend storage service for async results provided by Redis
  redis:
    container_name: redis
    image: redis
    hostname: redis
    # use the redis_entrypoint
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - main_network

networks:
  main_network: