version: "3.8"

services:
  web:
    environment:
      - ENV=development

      # db variables
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET

      # Django settings.py
      - DJANGO_SETTINGS_MODULE