"""
This docker-compose expands on the base one by passing on ENVs from the local container environment
on Github Actions. Also, it does not include the volume setting as the Github environment does not
have a pre-set space.
"""

version: "3.8"

services:
  web:
    environment:
      - ENV

      # db variables
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - SECRET

      # Django settings.py
      - DJANGO_SETTINGS_MODULE
  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB