version: "3.8"

services:
  # certbot
  certbot:
    build:
      context: ./docker/certbot
      dockerfile: Dockerfile.certbot
    command: echo "Skipping..."
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${ACME_DEFAULT_EMAIL}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - proxy
    networks:
      - main-network

  # nginx
  proxy:
    build:
      context: ./docker/proxy
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
      - static-files:/vol/static
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - api
    networks:
      - main-network

  # django service
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.python
    command: ["sh", "scripts/run_prod.sh"]
    restart: always
    depends_on:
      - celery
    ports:
      - "3001:3001"
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      STRIPE_API_TEST_KEY: ${STRIPE_API_TEST_KEY}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      DATABASE_URL: ${DATABASE_URL}
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
      REDIS_URL: ${REDIS_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    networks:
      - main-network
    volumes:
      - static-files:/app/static

  # Celery service
  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.python
    command: celery -A secure_my_spot.celeryconf worker --loglevel=INFO
    restart: always
    environment:
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      STRIPE_API_TEST_KEY: ${STRIPE_API_TEST_KEY}
      DOPPLER_CONFIG: ${DOPPLER_CONFIG}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
      DATABASE_URL: ${DATABASE_URL}
      CLOUDAMQP_URL: ${CLOUDAMQP_URL}
      REDIS_URL: ${REDIS_URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

networks:
  main-network:
    driver: bridge

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  static-files: