# Generated by Django 3.2.7 on 2021-10-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_parkingspots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspots',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parkingspots',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
