# Generated by Django 3.2.7 on 2021-10-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211009_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingSpots',
            new_name='ParkingSpot',
        ),
    ]
