# Generated by Django 3.2.7 on 2021-10-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211010_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='parkingspot',
            old_name='longitude',
            new_name='lng',
        ),
    ]
