# Generated by Django 3.2.8 on 2021-10-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211016_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='active',
            field=models.BooleanField(default=True, help_text='Is the parking spot commercially available to users'),
        ),
    ]
