# Generated by Django 3.2.8 on 2021-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='hourly rate in USD with 2 decimals', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, help_text='email of the unauthenticated user', max_length=254),
        ),
    ]
