# Generated by Django 3.2.9 on 2021-11-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211103_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(help_text='email of the user', max_length=254),
        ),
    ]
