# Generated by Django 3.2.9 on 2022-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment intent id issued by Stripe for setting up a payment intent', max_length=200),
        ),
    ]
