# Generated by Django 3.2.9 on 2022-01-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reservation_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, help_text='issued by Stripe for setting up a setup intent', max_length=200),
        ),
    ]
